import 'dart:convert';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sqflite/sqflite.dart';
import '../../models/intake_record.dart';
import '../../models/medicine.dart';
import '../../models/reminder_time.dart';
import '../../models/user_profile.dart';
import '../database/db_helper.dart';

class LocalRestoreResult {
  final bool success;
  final String message;
  final int profiles;
  final int medicines;
  final int reminders;
  final int records;

  const LocalRestoreResult({
    required this.success,
    required this.message,
    this.profiles = 0,
    this.medicines = 0,
    this.reminders = 0,
    this.records = 0,
  });
}

class LocalBackupService {
  static final LocalBackupService instance = LocalBackupService._init();
  LocalBackupService._init();

  static const String prefKeyLastBackupTime = 'local_last_backup_time';

  /// Returns the formatted last backup timestamp or null
  Future<String?> getLastBackupTime() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(prefKeyLastBackupTime);
  }

  /// Exports all local SQLite data into a formatted JSON backup file
  /// and opens the Android native share/save sheet so the user can
  /// save to Downloads, Google Drive, WhatsApp, Files, etc.
  Future<bool> exportBackup() async {
    try {
      final db = DBHelper.instance;

      // 1. Fetch all local SQLite data
      final profiles = await db.getAllProfiles();
      final medicines = await db.getAllMedicines();
      final List<Map<String, dynamic>> allReminders = [];

      for (final med in medicines) {
        final rems = await db.getRemindersForMedicine(med.id);
        for (final r in rems) {
          allReminders.add(r.toMap());
        }
      }

      final records = await db.getAllRecords(limit: 50000);

      // 2. Structure backup package
      final now = DateTime.now();
      final backupData = {
        'app': 'MediRemind',
        'version': '1.0.0',
        'schemaVersion': 1,
        'exportTimestamp': now.toIso8601String(),
        'profiles': profiles.map((p) => p.toMap()).toList(),
        'medicines': medicines.map((m) => m.toMap()).toList(),
        'reminders': allReminders,
        'intakeRecords': records.map((r) => r.toMap()).toList(),
      };

      // 3. Write to temporary JSON file
      final jsonString = const JsonEncoder.withIndent('  ').convert(backupData);
      final tempDir = await getTemporaryDirectory();
      final dateTag = DateFormat('yyyyMMdd_HHmmss').format(now);
      final fileName = 'MediRemind_Backup_$dateTag.json';
      final file = File('${tempDir.path}/$fileName');
      await file.writeAsString(jsonString, flush: true);

      // 4. Update last backup timestamp
      final formattedTime = DateFormat('dd MMM yyyy, hh:mm a').format(now);
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(prefKeyLastBackupTime, formattedTime);

      // 5. Open native Android share / save dialog
      final xFile = XFile(file.path, mimeType: 'application/json', name: fileName);
      final result = await Share.shareXFiles(
        [xFile],
        subject: 'MediRemind Health Backup ($dateTag)',
        text: 'MediRemind local medication backup exported on $formattedTime.',
      );

      return result.status == ShareResultStatus.success || result.status == ShareResultStatus.dismissed;
    } catch (e) {
      debugPrint('Error exporting local backup: $e');
      return false;
    }
  }

  /// Opens the native file picker to allow the user to select a JSON backup file.
  /// Validates and imports all profiles, medicines, reminders, and intake records into SQLite.
  Future<LocalRestoreResult> importBackup() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['json'],
      );

      if (result == null || result.files.isEmpty) {
        return const LocalRestoreResult(success: false, message: 'No file selected.');
      }

      final path = result.files.single.path;
      if (path == null) {
        return const LocalRestoreResult(success: false, message: 'Unable to access selected file path.');
      }

      final file = File(path);
      final jsonString = await file.readAsString();
      final Map<String, dynamic> data = jsonDecode(jsonString) as Map<String, dynamic>;

      // Validate schema signature
      if (data['app'] != 'MediRemind') {
        return const LocalRestoreResult(
          success: false,
          message: 'Invalid backup file. This file was not generated by MediRemind.',
        );
      }

      final db = DBHelper.instance;
      final rawDb = await db.database;

      int profilesRestored = 0;
      int medicinesRestored = 0;
      int remindersRestored = 0;
      int recordsRestored = 0;

      await rawDb.transaction((txn) async {
        // 1. Restore Profiles
        if (data['profiles'] is List) {
          for (final pMap in (data['profiles'] as List)) {
            if (pMap is Map<String, dynamic>) {
              try {
                final profile = UserProfile.fromMap(pMap);
                await txn.insert('profiles', profile.toMap(), conflictAlgorithm: ConflictAlgorithm.replace);
                profilesRestored++;
              } catch (_) {}
            }
          }
        }

        // 2. Restore Medicines
        if (data['medicines'] is List) {
          for (final mMap in (data['medicines'] as List)) {
            if (mMap is Map<String, dynamic>) {
              try {
                final med = Medicine.fromMap(mMap);
                await txn.insert('medicines', med.toMap(), conflictAlgorithm: ConflictAlgorithm.replace);
                medicinesRestored++;
              } catch (_) {}
            }
          }
        }

        // 3. Restore Reminders
        if (data['reminders'] is List) {
          for (final rMap in (data['reminders'] as List)) {
            if (rMap is Map<String, dynamic>) {
              try {
                final rem = ReminderTime.fromMap(rMap);
                await txn.insert('reminder_times', rem.toMap(), conflictAlgorithm: ConflictAlgorithm.replace);
                remindersRestored++;
              } catch (_) {}
            }
          }
        }

        // 4. Restore Intake Records
        if (data['intakeRecords'] is List) {
          for (final recMap in (data['intakeRecords'] as List)) {
            if (recMap is Map<String, dynamic>) {
              try {
                final record = IntakeRecord.fromMap(recMap);
                await txn.insert('intake_records', record.toMap(), conflictAlgorithm: ConflictAlgorithm.replace);
                recordsRestored++;
              } catch (_) {}
            }
          }
        }
      });

      return LocalRestoreResult(
        success: true,
        message: 'Restored $medicinesRestored medicines & $recordsRestored dose records successfully.',
        profiles: profilesRestored,
        medicines: medicinesRestored,
        reminders: remindersRestored,
        records: recordsRestored,
      );
    } catch (e) {
      debugPrint('Error importing local backup: $e');
      return LocalRestoreResult(success: false, message: 'Restore error: $e');
    }
  }
}
